global:
  resolve_timeout: 1m

  smtp_smarthost: smtp.gmail.com:587
  smtp_from: myemail@gmail.com
  smtp_auth_username: myemail@gmail.com
  smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password
  smtp_require_tls: true

route:
  receiver: api-monitoring-notifications
  group_by:
    - alertname
    - severity
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: api-monitoring-notifications

    webhook_configs:
      - url: http://alert_receiver:8080/alerts
        send_resolved: true

    email_configs:
      - to: myemail@gmail.com
        from: myemail@gmail.com
        send_resolved: true
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        channel: "#api-alerts"
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }} - {{ .Annotations.description }}{{ end }}'
