global:
  resolve_timeout: 1m

  smtp_smarthost: smtp.gmail.com:587
  smtp_from: userbroofthenation@gmail.com
  smtp_auth_username: userbroofthenation@gmail.com
  smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password
  smtp_require_tls: true

route:
  receiver: api-monitoring-notifications
  group_by:
    - alertname
    - severity
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: api-monitoring-notifications

    webhook_configs:
      - url: http://alert_receiver:8080/alerts
        send_resolved: true

    email_configs:
      - to: userbroofthenation@gmail.com
        from: userbroofthenation@gmail.com
        send_resolved: true